name: Just Test with Playwright

on:
  # Runs on pushes targeting the default branch
  push:
    branches: "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npx playwright install chromium
          npm install lint format build
          npm install -g lighthouse
          npm install 

      - name: Run tests
        run: npm run test

      - name: Start local server
        run: npm start &

      - name: Wait for server to start
        run: npx wait-on http://localhost:3000

      - name: Generate Lighthouse report
        run: lighthouse http://localhost:3000 --output html --output-path ./test-results/report.html

      - name: Upload test results and Lighthouse report
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            ./test-results
            ./test-results/report.html
            
